GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/5ebb2de7d7bab729022290c9

###

GET http://localhost:3001/api/personsx

###

DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons
content-type: application/json

{
	"name": "ty",
	"number": "12sd222256" 
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
	"name": "testname"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
	"number": "12356" 
}